version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.4.8-jessie
    working_directory: ~/repo
    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "requirements.txt" }}
        - v1-dependencies-

    - run:
      name: Install MeCab
      command: |
        apt-get update;
        apt-get -y install mecab libmecab-dev mecab-ipadic-utf8


    - run:
      name: install dependencies
      command: |
        python3 -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt

    - save_cache:
        paths:
        - ./venv
        key: v1-dependencies-{{ checksum "requirements.txt" }}

    - run:
        name: run tests
        command: |
          . venv/bin/activate
          pytest

    - store_artifacts:
        path: test-reports
        destination: test-reports
          